server:
  port: 8888

spring:
  application:
    name: cofound-service
#  rabbitmq:
#    host: 127.0.0.1
#    port: 5672
#    username: guest
#    password: guest
  profiles:
    active: git
  cloud:
    config:
      server:
#        native:
#          search-locations: file:///D:\_Study/Spring_Cloud/native-file-repo
        git:
#          uri: file://D:\_Study\Spring_Cloud\git-local-repo
            uri: https://github.com/lee-seokjun/spring-cloud-config.git
            default-label: master
#            username:
#            password:
management:
  endpoints:
    web:
      exposure:
        include: health, busrefresh

