spring:
  security:
    user:
      name: user
      password: 1234
  profiles:
    active: local
  jpa:
    defer-datasource-initialization: true
  application:
    name: TEST-SERVICE
  config:
    import: "optional:configserver:"
  cloud:
    config:
      uri: http://127.0.0.1:8888
      name: user-service
      enabled: true
  main:
    allow-bean-definition-overriding : true

#  h2:
#    console:
#      enabled: true
#      path: "/h2-console"
#      settings:
#        web-allow-others: true


test:
  test: test
accessible:
  user:
    address: 127.0.0.1
eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka
# actuator 추가
management:
  endpoints:
    web:
      exposure:
        include: refresh, health, beans, busrefresh, info, metrics, prometheus,env